apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: myalias=233561708035.dkr.ecr.ap-south-1.amazonaws.com/ecr-sd5294-devops-frontend:*
    argocd-image-updater.argoproj.io/write-back-method: git       
    argocd-image-updater.argoproj.io/git-branch: main      
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    argocd-image-updater.argoproj.io/myalias.force-update: "true"
spec:
  project: frontend
  source:
    repoURL: https://github.com/ToanLeH/sd2079_msa
    targetRevision: HEAD
    path: ./deploy/frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: app-argocd
  syncPolicy:
    automated:
      selfHeal: true 
      prune: false